#cloud-config

# /var/lib/rancher/conf/cloud-config.d/nfs.yml

# https://github.com/rancher/os/issues/641
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    content: |
      #!/bin/bash
      [ ! -e /usr/bin/docker ] && ln -s /usr/bin/docker.dist /usr/bin/docker

rancher:
  services:
    nfs:
      image: fincaminimo/docker-nfs-client
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      - /mnt/efs:/mnt/nfs-1:shared
      environment:
        SERVER: fs-bf32fd76.efs.eu-west-1.amazonaws.com
        SHARE: /
        MOUNTPOINT: /mnt/efs
        FS_TYPE: nfs4
        MOUNT_OPTIONS: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
