#cloud-config

# example to use nfs storage client
rancher:
  services:
    nfs:
      image: aeilers/docker-nfs-client
      labels:
        io.rancher.os.after: console
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
      environment:
        SERVER: 172.16.0.2
        SHARE: /share/location
mounts:
  - ["172.16.0.2:/share/location", "/mnt/nfs", "nfs", ""]
